spring:
    application:
        name: Telegram-Service
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: root
        password: privet
bot:
    name: "InvestmentNotificationBot"
    token: "7402051299:AAGgNIrpivh1h6C5EDDPcU_Z5Ce-yi_yTmo"
scheduling:
    fixed-rate: 50000