spring:
    application:
        name: Telegram-Service
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: root
        password: admin
bot:
    name: "InvestmentNotificationBot"
    token: "TOKEN"
scheduling:
    fixed-rate: 300000