services:
  dbservice:
    build:
      context: /DB-Service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - database
      - rabbimq
  database:
    image: postgres:16
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "investmentDB"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
  investmentservice:
    build:
      context: /Investment-Service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - rabbimq
  telegramservice:
    build:
      context: /Telegram-Service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - rabbimq
  rabbimq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
      - rabbitmq-logs:/var/lib/rabbitmq
    restart: always

volumes:
  db-data: {}
  rabbitmq-data: {}
  rabbitmq-logs: {}