spring:
    application:
        name: DB-Service
    rabbitmq:
        host: rabbitmq
        port: 5672
        username: root
        password: admin
    datasource:
        url: jdbc:postgresql://database:5432/investmentDB
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        generate-ddl: true



#        url: jdbc:postgresql://localhost:5432/postgres